NAME = game

FLAG =  c++

FLAGS =  -Wall -Wextra -Werror -std=c++98
 
HEADER =  ./AMateria.hpp  ./Character.hpp ./Cure.hpp ./Ice.hpp ./ICharacter.hpp ./IMateriaSource.hpp ./MateriaSource.hpp 
SRC = ./main.cpp  ./AMateria.cpp  ./Character.cpp ./Cure.cpp ./Ice.cpp ./MateriaSource.cpp 


OBJ =  $(SRC:.cpp=.o)

all : $(NAME)


$(NAME) : $(OBJ) 
		$(FLAG) $(FLAGS)  $^ -o $@


%.o : %.cpp ${HEADER} 
	$(FLAG) $(FLAGS)  $< -c -o $@ 

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME) 

re: fclean all 